version: '3'

services:
  sonarqube:
      image: sonarqube
      restart: unless-stopped
      ports:
        - 0.0.0.0:9000:9000
        - 0.0.0.0:9092:9092
      networks:
       - nexus
  server:
    image: danielk999/ci-cd:multistage_compose 
    build: 
      context: .
      dockerfile: Dockerfile-pipelines
    networks:
      - nexus
    depends_on:
      - sonarqube
networks:
  nexus:
