node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('DockerBuild') {
       dir("advance/multistage_build"){
       sh "docker build --target builder -t danielk999/ci-cd:multi_stage_builder -f Dockerfile-pipelines ."
       }
     }
   stage('Linting') {
       dir("advance/multistage_build"){
       sh "docker build --target linting -t danielk999/ci-cd:multi_stage_test -f Dockerfile-pipelines ."
       }
    }
   stage('push') {
      withCredentials([usernamePassword{credentialsId:"dockerhub", usernameVariable:"USERNAME", passwordVariable:"PASS"}]){
        dir("advance/multistage_build"){
          sh "docker login -u ${USERNAME} -p ${PASS}"
          sh "docker push danielk999/ci-cd:multi_stage_test"
        }
      }
    }
}
   
   




